### ISSUE TITLE
Add support of multiple terraform configurations

### ISSUE THREAD

**Issue by anosulchik** [newcontext-oss/kitchen-terraform#146]
Some time ago we started using kitchen-terraform to test aws resources created by our terraform configurations but we got stuck on the case described below.

Our terraform config consists of two parts: cluster part and web service part. Cluster part create ASG, load balancer and it can be tested with kitchen-terraform like a charm. Web service part refers resources of cluster part (e.g. creates ECS services attached to ELB in cluster part). For example:

Wer service refers S3 remote state of cluster part:

```
data "terraform_remote_state" "cluster" {
  backend = "s3"
  config {
    region = "us-east-1"

    bucket = "${var.shared_cluster_remote_state_s3_bucket}"
    key = "${var.shared_cluster_remote_state_s3_key}"

    encrypt = "true"
    kms_key_id = "${var.shared_cluster_remote_state_kms_key_id}"
  }
}
```

And we refer outputs of cluster part like below:

```
resource "aws_ecs_service" "ecs_service" {
  name = "tf-${var.service_name}-${var.environment_name}"
  cluster = "${data.terraform_remote_state.cluster.ecs_cluster_name}"
  ...
}
```

So, in order to create and then test webservice resources we need to somehow create cluster first. Now we do it manually and it cannot be easily automated.

Is this possible to configure kitchen-terraform to converge cluster terraform configuration (e.g. by specifying path to github repo with cluster terraform config) prior to converging web service part?

Thanks for your reply in advance.

**Comment by ncs-alane** [comment]
@anosulchik 
One way to accomplish what you described would be to leverage Test Kitchen's support for overriding global plugin configuration attributes for specific suites. This will allow you to define a fixture module which initializes the remote cluster state prior to converging the web module.

# Example .kitchen.yml Snippet
```yaml
driver:
  name: terraform
suites:
  -
    name: cluster
    driver:
      directory: "path/to/cluster/module"
  -
    name: web
    driver:
      directory: "path/to/web/module"
```

To orchestrate the process, you could use [Rake](https://rubygems.org/gems/rake) and [Test Kitchen's Rake Tasks](https://github.com/test-kitchen/test-kitchen/blob/v1.16.0/lib/kitchen/rake_tasks.rb).

**Comment by anosulchik** [comment]
@ncs-msmith Thanks for your reply! Let me provide more information about our case. In order to link webservice configuration with cluster one, we need to setup terraform remote s3 backend for cluster and then refer it in webservice configuration so we the possibility to configure terraform driver in kitchen differently for both suites. So we end up with the following setup:

```
---
provisioner:
  name: terraform

platforms:
  - name: default

verifier:
      name: "terraform"
      groups:
        -
          name: "local"
          controls:
            - "ecs"
            - "iam"
            - "alb"
            - "cloudwatch"

suites:
  - name: cluster
    driver:
      name: "terraform"
      directory: "/path/to/cluster"
      backend_configurations:
        region: "us-east-1"
        bucket: "bucket"
        key: "soa-aws-stack-v2/cluster/test/terraform.tfstate"
        kms_key_id: "111"
        dynamodb_table: "terraform-locks"
      variable_files:
        - "test/cluster.tfvars"
  - name: webservice
    driver:
      name: "terraform"
      directory: "/path/to/webservice"
      backend_configurations:
        region: "us-east-1"
        bucket: "bucket"
        key: "soa-aws-stack-v2/cluster/webservice/test/terraform.tfstate"
        kms_key_id: "111"
        dynamodb_table: "terraform-locks"
      variable_files:
        - "test/webservice.tfvars"
```

Now I can converge cluster before running tests for webservice:

```
aws-profile devortex-dev bundle exec kitchen converge cluster-default
aws-profile devortex-dev bundle exec kitchen test webservice-default
```

But we have different configurations of verifiers for webservice and cluster. Is this possible to specify different set of controls for cluster and webservice. Thanks in advance!
