### ISSUE TITLE
Invoke recipes before integration tests

### ISSUE THREAD

**Issue by marekmrowca** [newcontext-oss/kitchen-terraform#147]
Hi,
Is it possible to run a run_list with terraform verifier?
For vagrant driver I define the inspec verifier and the following suite:
```
suites:
  - name: default
    run_list:
      - recipe[testProject2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
```

It applies recipes defined in run_list before executing tests. However, I don't know how to do the same with terraform verifier:
```
verifier:
  name: terraform
  groups:
    - name: default
      controls:
        - operating_system
      hostnames: public_dns
```

I tried with different configuration of both, e.g. including "run_list" option in "groups", running "suites" section along with terraform verifier, but with no luck.

Could you please help?
Best regards,
Marek
