### ISSUE TITLE
Can no longer pass in ENV vars to the driver variables hash

### ISSUE THREAD

**Issue by ryancurrah** [newcontext-oss/kitchen-terraform#157]
We used to be able to pass in environment variables to the kitchen-terraform driver `variables` hash from Jenkins to the `.kitchen.yml` file but now there is a check that prevents this. https://github.com/newcontext-oss/kitchen-terraform/blob/b36684edb19fc0bb8340b557f7d4b693e4c36e32/lib/kitchen/terraform/config_predicates/hash_of_symbols_and_strings.rb#L48-L72 Is it possible to loosen up the check so that we may still use this syntax?

**Versions**

Ruby version: `2.3.3`
Kitchen version: `1.19.1`
Kitchen-terraform version: `2.1.0`
Terraform version: `0.10.8`

**.kitchen.yml**

```yaml
---
driver:
  name: terraform
  directory: terraform
  command_timeout: 600
  color: true
  variables:
    vsphere_server: <%= ENV['VSPHERE_SERVER'] %>
    vsphere_user: <%= ENV['VSPHERE_USER'] %>
    vsphere_password: <%= ENV['VSPHERE_PASS'] %>
    vmw_image_name: <%= ENV['VMW_IMAGE_NAME'] %>
    vmw_instance_name: <%= ENV['VMW_INSTANCE_NAME'] %>

provisioner:
  name: terraform

platforms:
  - name: rhel7

transport:
  name: ssh
  ssh_key: packer-ssh-key
  connection_timeout: 10
  connection_retries: 20

verifier:
  name: terraform
  format: junit
  output: inspec_output.xml
  sudo: true
  groups:
    - name: core-rhel7
      hostnames: instance_ip
      username: packer

suites:
  - name: core-rhel7
```

**Error output**

```ruby
kitchen test --destroy always
-----> Starting Kitchen (v1.19.1)
       Terraform v0.10.8
       
       Your version of Terraform is out of date! The latest version
       is 0.11.0. You can update by downloading from www.terraform.io/downloads.html
$$$$$$ Terraform version 0.10.8 is supported
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Kitchen::Driver::Terraform configuration: variables {:value=>["must be a hash which includes only symbol keys and string values"]}
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
