### ISSUE TITLE
kitchen terraform doesn't respect existing backend configuration

### ISSUE THREAD

**Issue by zambien** [newcontext-oss/kitchen-terraform#220]
Hello,

I am working on setting up kitchen-terraform for our existing provisioned infrastructure with the goal of doing better testing and of using kitchen-terraform to provision/test in all of our environments.  I have noticed that if I have an existing backend config that kitchen-terraform prepends s3 object paths to that.  For example, if my config is:

```
---
driver:
  name: terraform
  backend_configurations:
    region: "us-east-1"
    profile: "some-profile"
    bucket: "some-profile.somedomain.net"
    key: "my-org/my-app/lab2/terraform-lab2.tfstate"
    acl: "private"
    dynamodb_table: "myapp-terraform-locktable"
  variable_files:
    - ./environments/some-profile-lab2.tfvars
```

I would expect that kitchen-terraform would use the s3 path of:

```
# not a real path
s3://some-profile.somedomain.net/my-org/my-app/lab2/terraform-lab2.tfstate
```
for remote state.

But what actually gets set is:

```
# again, not a real path
s3://some-profile.somedomain.net/env:/kitchen-terraform-default-ubuntu/my-org/my-app/lab2/terraform-lab2.tfstate
```

Where `env:/kitchen-terraform-default-ubuntu/` was unexpected.

I can of course copy my existing tfstate file over to the expected path with the additional `env:/kitchen-terraform-default-ubuntu/` path but thought to ask about this here first.  I can see in the gemspec doc that it mentions something about this:

`
terraform workspace <select|new> kitchen-terraform-<instance>
`

What do you all think about this issue?  Also, is using kitchen-terraform to deploy in all envs (and not just for testing in lower envs) an anticipated use case of the tool?

Thanks for the awesome set of libraries!
