### ISSUE TITLE
inspec target is using wrong target in kitchen-terraform from the example

### ISSUE THREAD

**Issue by albertux** [newcontext-oss/kitchen-terraform#241]
####  the current test will fail replace this line in this file: ./test/integration/example/controls/operating_system.rb
```diff
6c6
<       command("lsb_release -a").stdout
---
>       command("cat /etc/os-release").stdout
```
####  testing inspec alone works fine
```sh
$ inspec exec test/integration/example/controls/operating_system.rb -t ssh://root:root@localhost:2222  

Profile: tests from test/integration/example/controls/operating_system.rb (tests from test.integration.example.controls.operating_system.rb)
Version: (not specified)
Target:  ssh://root@localhost:2222

  ✔  operating_system: the operating system
     ✔  the operating system is Ubuntu


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 1 successful, 0 failures, 0 skipped
```
#### kitchen test has a wrong inspect target 
```sh
$ bundle exec kitchen test
-----> Starting Kitchen (v1.21.2)
$$$$$$ Running command `terraform version`
       Terraform v0.11.7
       + provider.docker v0.1.1

$$$$$$ Terraform v0.11.7 is supported
-----> Cleaning up any prior instances of <example-ubuntu>
-----> Destroying <example-ubuntu>...
$$$$$$ Running command `terraform init -input=false -lock=true -lock-timeout=0s -no-color -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /Users/albertoa/example1`

       Initializing provider plugins...

       The following providers do not have any version constraints in configuration,
       so the latest version was installed.

       To prevent automatic upgrades to new major versions that may contain breaking
       changes, it is recommended to add version = "..." constraints to the
       corresponding provider blocks in configuration, with the constraint strings
       suggested below.

       * provider.docker: version = "~> 0.1"

       Terraform has been successfully initialized!
$$$$$$ Running command `terraform workspace select kitchen-terraform-example-ubuntu`
$$$$$$ Running command `terraform destroy -force -lock=true -lock-timeout=0s -input=false -no-color -parallelism=10 -refresh=true   /Users/albertoa/example1`
       data.docker_registry_image.ubuntu: Refreshing state...
       docker_image.ubuntu: Refreshing state... (ID: sha256:49533628fb371c9f1952c06cedf912c7...9376e077erastasheep/ubuntu-sshd:latest)
       docker_container.ubuntu: Refreshing state... (ID: 2dfe8d9fd2126c886da2d5ede6de1365e0aac800877cae2dd1337dd441065924)
       docker_container.ubuntu: Destroying... (ID: 2dfe8d9fd2126c886da2d5ede6de1365e0aac800877cae2dd1337dd441065924)
       docker_container.ubuntu: Destruction complete after 1s
       docker_image.ubuntu: Destroying... (ID: sha256:49533628fb371c9f1952c06cedf912c7...9376e077erastasheep/ubuntu-sshd:latest)
       docker_image.ubuntu: Destruction complete after 0s

       Destroy complete! Resources: 2 destroyed.
$$$$$$ Running command `terraform workspace select default`
       Switched to workspace "default".
$$$$$$ Running command `terraform workspace delete kitchen-terraform-example-ubuntu`
       Deleted workspace "kitchen-terraform-example-ubuntu"!
       Finished destroying <example-ubuntu> (0m2.70s).
-----> Testing <example-ubuntu>
-----> Creating <example-ubuntu>...
$$$$$$ Running command `terraform init -input=false -lock=true -lock-timeout=0s -no-color -upgrade -force-copy -backend=true  -get=true -get-plugins=true  -verify-plugins=true /Users/albertoa/example1`

       Initializing provider plugins...
       - Checking for available provider plugins on https://releases.hashicorp.com...
       - Downloading plugin for provider "docker" (0.1.1)...

       The following providers do not have any version constraints in configuration,
       so the latest version was installed.

       To prevent automatic upgrades to new major versions that may contain breaking
       changes, it is recommended to add version = "..." constraints to the
       corresponding provider blocks in configuration, with the constraint strings
       suggested below.

       * provider.docker: version = "~> 0.1"

       Terraform has been successfully initialized!
$$$$$$ Running command `terraform workspace select kitchen-terraform-example-ubuntu`

       Workspace "kitchen-terraform-example-ubuntu" doesn't exist.

       You can create this workspace with the "new" subcommand.
$$$$$$ Running command `terraform workspace new kitchen-terraform-example-ubuntu`
       Created and switched to workspace "kitchen-terraform-example-ubuntu"!

       You're now on a new, empty workspace. Workspaces isolate their state,
       so if you run "terraform plan" Terraform will not see any existing state
       for this configuration.
       Finished creating <example-ubuntu> (0m1.23s).
-----> Converging <example-ubuntu>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-example-ubuntu`
$$$$$$ Running command `terraform get -update /Users/albertoa/example1`
$$$$$$ Running command `terraform validate -check-variables=true -no-color   /Users/albertoa/example1`
$$$$$$ Running command `terraform apply -lock=true -lock-timeout=0s -input=false -auto-approve=true -no-color -parallelism=10 -refresh=true   /Users/albertoa/example1`
       data.docker_registry_image.ubuntu: Refreshing state...
       docker_image.ubuntu: Creating...
         latest:                  "" => "<computed>"
         name:                    "" => "rastasheep/ubuntu-sshd:latest"
         pull_triggers.#:         "" => "1"
         pull_triggers.271913834: "" => "sha256:1a4010f95f6b3292f95fb26e442f85885d523f9a0bb82027b718df62fdd0d9e9"
       docker_image.ubuntu: Still creating... (10s elapsed)
       docker_image.ubuntu: Creation complete after 20s (ID: sha256:49533628fb371c9f1952c06cedf912c7...9376e077erastasheep/ubuntu-sshd:latest)
       docker_container.ubuntu: Creating...
         bridge:                   "" => "<computed>"
         gateway:                  "" => "<computed>"
         image:                    "" => "rastasheep/ubuntu-sshd:latest"
         ip_address:               "" => "<computed>"
         ip_prefix_length:         "" => "<computed>"
         log_driver:               "" => "json-file"
         must_run:                 "" => "true"
         name:                     "" => "ubuntu_container"
         ports.#:                  "" => "1"
         ports.265401579.external: "" => "2222"
         ports.265401579.internal: "" => "22"
         ports.265401579.ip:       "" => ""
         ports.265401579.protocol: "" => "tcp"
         restart:                  "" => "no"
       docker_container.ubuntu: Creation complete after 0s (ID: cf886c83ac4ee17fcea771004fa37695cc64c0a3cea514c73f28ba51c26215ac)

       Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
$$$$$$ Running command `terraform output -json`
       The state file either has no outputs defined, or all the defined
       outputs are empty. Please define an output in your configuration
       with the `output` keyword and run `terraform refresh` for it to
       become available. If you are using interpolation, please verify
       the interpolated value is not empty. You can use the
       `terraform console` command to assist.
       Finished converging <example-ubuntu> (0m21.90s).
-----> Setting up <example-ubuntu>...
       Finished setting up <example-ubuntu> (0m0.00s).
-----> Verifying <example-ubuntu>...
       Verifying host 'localhost' of group 'container'
       Loaded example

Profile: example
Version: (not specified)
Target:  local://

  ×  operating_system: the operating system
     ×  the operating system is Ubuntu
     expected "" to match /Ubuntu/
     Diff:
     @@ -1,2 +1,2 @@
     -/Ubuntu/
     +""



Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <example-ubuntu>.  Please see .kitchen/logs/example-ubuntu.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
```sh
$ kitchen diagnose --all
$$$$$$ Running command `terraform version`
       Terraform v0.11.7
       + provider.docker v0.1.1
       
$$$$$$ Terraform v0.11.7 is supported
```
```yaml
---
timestamp: 2018-05-28 12:48:11 UTC
kitchen_version: 1.21.2
plugins:
  driver:
    Terraform:
      class: Kitchen::Driver::Terraform
      version: 3.3.1
      api_version: 2
  provisioner:
    Terraform:
      class: Kitchen::Provisioner::Terraform
      version: 3.3.1
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.21.2
      api_version: 1
  verifier:
    Terraform:
      class: Kitchen::Verifier::Terraform
      version: 3.3.1
      api_version: 2
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config: 
  project_config:
    filename: "/Users/albertoa/example1/.kitchen.yml"
    raw_data:
      driver:
        name: terraform
      provisioner:
        name: terraform
      transport:
        name: ssh
        password: root
      verifier:
        name: terraform
        groups:
        - name: container
          port: 2222
          username: root
      platforms:
      - name: ubuntu
      suites:
      - name: example
  local_config: 
  combined_config:
    filename: 
    raw_data:
      driver:
        name: terraform
      provisioner:
        name: terraform
      transport:
        name: ssh
        password: root
      verifier:
        name: terraform
        groups:
        - name: container
          port: 2222
          username: root
      platforms:
      - name: ubuntu
      suites:
      - name: example
instances:
  example-ubuntu:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      kitchen_terraform_group:
        name: container
        port: 2222
        username: root
      kitchen_terraform_hostname: localhost
      kitchen_terraform_output: {}
      last_action: setup
      last_error: Kitchen::ActionFailed
    driver:
      backend_configurations: {}
      color: false
      command_timeout: 600
      kitchen_root: "/Users/albertoa/example1"
      lock: true
      lock_timeout: 0
      log_level: :info
      name: terraform
      parallelism: 10
      plugin_directory: 
      pre_create_command: 
      root_module_directory: "/Users/albertoa/example1"
      test_base_path: "/Users/albertoa/example1/test/integration"
      variable_files: []
      variables: {}
    provisioner:
      command_prefix: 
      debug: 
      downloads: {}
      ftp_proxy: 
      http_proxy: 
      https_proxy: 
      kitchen_root: "/Users/albertoa/example1"
      max_retries: 1
      name: terraform
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/Users/albertoa/example1/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/Users/albertoa/example1"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      password: root
      port: 22
      ssh_gateway: 
      ssh_gateway_username: 
      ssh_http_proxy: 
      ssh_http_proxy_password: 
      ssh_http_proxy_port: 
      ssh_http_proxy_user: 
      ssh_key: 
      test_base_path: "/Users/albertoa/example1/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      color: false
      command_prefix: 
      debug: 
      ftp_proxy: 
      groups:
      - name: container
        port: 2222
        username: root
      http_proxy: 
      https_proxy: 
      inspec_tests: []
      kitchen_root: "/Users/albertoa/example1"
      log_level: :info
      name: terraform
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: example
      test_base_path: "/Users/albertoa/example1/test/integration"
```
