### ISSUE TITLE
verify command runs tests twice

### ISSUE THREAD

**Issue by walterdolce** [newcontext-oss/kitchen-terraform#253]
I have the following `.kitchen.yml` file:
```
---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: terraform

suites:
  - name: default
    verifier:
      backend: local
      groups:
        - name: local_pre_reqs
  - name: gcp
    verifier:
      backend: gcp
      groups:
        - name: gcp_base_reqs
        - name: master_nodes
```

And the following folders structure:
<img width="316" alt="screen shot 2018-07-22 at 00 18 02" src="https://user-images.githubusercontent.com/6195629/43040789-c7d96dbc-8d44-11e8-8b08-d4722e8edf2d.png">

When I `verify` the changes, the tests are run twice for each group:
```
bundle exec kitchen verify gcp                                                                     6.7s
-----> Starting Kitchen (v1.22.0)
$$$$$$ Running command `terraform version`
       Terraform v0.11.7
       + provider.google v1.16.2

$$$$$$ Terraform v0.11.7 is supported
-----> Verifying <gcp-terraform>...
       Verifying host 'localhost' of group 'gcp_base_reqs'
       Loaded gcp

Profile: gcp
Version: (not specified)
Target:  gcp://random-id.apps.googleusercontent.com

  ✔  gcp-base-reqs: Verify basic GCP requirements
     ✔  Project  should exist
     ✔  Project  lifecycle_state should eq "ACTIVE"
  ✔  master-nodes-gcp: Verify K8s master nodes on GCP
     ✔  Instance k8s-master should exist
     ✔  Instance k8s-master status should eq "RUNNING"
     ✔  Instance k8s-master tags.items should include "foo"


Profile: Google Cloud Platform Resource Pack (inspec-gcp)
Version: 0.4.0
Target:  gcp://random-id.apps.googleusercontent.com

     No tests executed.

Profile Summary: 2 successful controls, 0 control failures, 0 controls skipped
Test Summary: 5 successful, 0 failures, 0 skipped
       Verifying host 'localhost' of group 'master_nodes'
       Loaded gcp

Profile: gcp
Version: (not specified)
Target:  gcp://random-id.apps.googleusercontent.com

  ✔  gcp-base-reqs: Verify basic GCP requirements
     ✔  Project  should exist
     ✔  Project  lifecycle_state should eq "ACTIVE"
  ✔  master-nodes-gcp: Verify K8s master nodes on GCP
     ✔  Instance k8s-master should exist
     ✔  Instance k8s-master status should eq "RUNNING"
     ✔  Instance k8s-master tags.items should include "foo"


Profile: Google Cloud Platform Resource Pack (inspec-gcp)
Version: 0.4.0
Target:  gcp://random-id.apps.googleusercontent.com

     No tests executed.

Profile Summary: 2 successful controls, 0 control failures, 0 controls skipped
Test Summary: 5 successful, 0 failures, 0 skipped
       Finished verifying <gcp-terraform> (0m3.79s).
-----> Kitchen is finished. (0m6.14s)
```

Note how when `Verifying host 'localhost' of group 'gcp_base_reqs'`,  also the tests for the group `master_nodes` are included and run, and vice-versa.

This doesn't seem to be expected behaviour. I would expect to have the group restrict the scope of what it's running. Am I right?

Unless I am misunderstanding the meaning of `groups`.

Thanks!

**Comment by ncs-alane** [comment]
What you are seeing is the expected behaviour. Groups do not automatically correlate to any particular controls in the InSpec profile. In order to achieve your desired behaviour, you need to explicitly filter the controls per group:

```yaml
groups:
  - name: gcp_base_reqs
    controls:
      - gcp-base-reqs
  - name: master_nodes
    controls:
      - master-nodes-gcp
```

With the release of Kitchen-Terraform v4.0.0, groups will have additional, distinguishing InSpec configuration attributes, but they will still share all controls from their associated profile by default.
