### ISSUE TITLE
[FR] Output terraform JSON into location

### ISSUE THREAD

**Issue by DavidJeche** [newcontext-oss/kitchen-terraform#264]
It would be great if we could output the JSON from a terraform run into a specific location. This will enable us to utilize that JSON in whatever verifier we may be using. I currently think copying the output and pasting it is the best path of action at the moment. 

The only problem I seem to be experiencing is that when I run a full kitchen test. The JSON is not accessible since you don't get a chance to copy/paste it.

**Comment by metmajer** [comment]
@DavidJeche I am interested in your solution but cannot quite follow your approach. Mind sharing a full example? Cheers!

**Comment by ncs-alane** [comment]
Hey @DavidJeche:
Not only are the Terraform outputs exposed as equivalently named InSpec attributes, but you can also use a verifier system's `attrs_outputs` attribute to map custom names of InSpec attributes and associate them with particular Terraform outputs.

```hcl
output "my_output" {
  value = "a_value"
}
```

```yaml
verifier:
  name: terraform
  systems:
    - name: a_system
      attrs_outputs:
        your_output: my_output
```

```ruby
my_output = attribute "my_output", {}
your_output = attribute "your_output", {}

my_output == your_output
# true
```

**Comment by DavidJeche** [comment]
@metmajer The idea is the when running terraform there are specific components that are dynamically generated when the run is occurring. It would be nice to pass these value into the the test since we are not able to. I can share some of the code when I do a push to the public repo.

```
driver:
  name: terraform
  variables:
    ami_values: placeholder

  root_module_directory: test/fixtures

provisioner:
  name: terraform

platforms:
  - name: aws

verifier:
  name: terraform
  systems:
  - name: default
    backend: aws
    controls:
      - initial

  - name: sshservice
    backend: ssh
    hosts_output: promtheus_server_ip
    sudo: true
    key_files:
      - ~/sshkey.pem
    controls:
      - operating_system
    user: ubuntu

suites:
  - name: prometheus_aws

```

--------

Thanks @ncs-alane that is super useful. It much appreciated.
