### ISSUE TITLE
Azure test case: undefined method `Microsoft` for #<Class:0x00000000031da6c0>

### ISSUE THREAD

**Issue by NTHINGs** [newcontext-oss/kitchen-terraform#267]
I'm trying to run this control:

```ruby
control "resource_group_test" do
  impact 1
  describe azure_resource_group(name: 'RG-dev-ea-test') do
    it { should_not exist }
  end
end
```
And I get the next exception:
```
×  resource_group_test: default/controls/test.rb:7
     ×  Control Source Code Error default/controls/test.rb:7
     undefined method `Microsoft` for #<Class:0x00000000031da6c0>

```
I have the next tree in my terraform module
.
├── main.tf
├── outputs.tf
├── test
│   ├── example
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── testing.tfvars
│   └── integration
│       └── default
│           ├── controls
│           │   └── test.rb
│           └── inspec.yml
└── variables.tf

My .kitchen.yml: 
```yaml
---
driver:
  name: "terraform"
  root_module_directory: "test/example"
  parallelism: 1
  variable_files:
    - "test/example/testing.tfvars"

provisioner:
  name: "terraform"

platforms:
  -
    name: "ubuntu"

verifier:
  name: "terraform"
  groups:
    -
      name: "local"
      controls:
        - "resource_group_test"

suites:
  - name: "default"
    verifier:
      systems: 
      - name: resource_group
        backend: azure
```

My inspec.yml:
```yaml
--- 
name: default 
version: 0.1.0
```

even running the control with `inspec exec default -t azure://` fails:
