### ISSUE TITLE
Escape character in backend configuration 

### ISSUE THREAD

**Issue by Groumy** [newcontext-oss/kitchen-terraform#283]
Hi

I'm trying to get started with kitchen-terraform but I encounter a weird issue.

My terraform use an Azure Backend with partial configurations to deploys some azure resource groups and stuff. 

## Error encountered 

When I execute  `kitchen create`  I receive this error :

```
C:\dev\az.flex.prod.gtd.fondationportail>exit
PS C:\dev\az.flex.prod.gtd.fondationportail> kitchen create
-----> Starting Kitchen (v1.23.2)
$$$$$$ Running command `terraform version` in directory C:/dev/az.flex.prod.gtd.fondationportail
       Terraform v0.11.8
       + provider.azurerm v1.16.0

$$$$$$ Terraform v0.11.8 is supported
-----> Creating <fondationportail-azure>...
$$$$$$ Running command `terraform init -input=false -lock=true -lock-timeout=0s  -upgrade -force-copy -backend=true -backend-config=arm_subscription_id\=SOME_GUID -backend-config=arm_client_id\=SOME_GUID -backend-config=arm_client_secret\=SOME_SECRET -backend-config=arm_tenant_id\=SOME_GUID-get=true -get-plugins=true  -verify-plugins=true` in directory C:/dev/az.flex.prod.gtd.fondationportail
       Upgrading modules...
       - module.peering
         Updating source "modules/peering"

       Initializing the backend...
       Error configuring the backend "azurerm": 4 error(s) occurred:

       * : invalid or unknown key: arm_client_secret\
       * : invalid or unknown key: arm_tenant_id\
       * : invalid or unknown key: arm_subscription_id\
       * : invalid or unknown key: arm_client_id\
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <fondationportail-azure>.  Please see .kitchen/logs/fondationportail-azure.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

As you can see, all my arguments have now a `\` after the name and before the `=`, causing an issue in terraform parsing. 

From what I understand the problem is caused by [the line 364 in the file /lib/kitchen/driver/terraform.rb](https://github.com/newcontext-oss/kitchen-terraform/blob/master/lib/kitchen/driver/terraform.rb#L361-L367). 

The Shell Escaping function escape de `=` between the key and the value. Maybe it should escape both separatly ?

I'm using this on Windows BTW, tried with both PowerShell and CMD with the same result

## Configuration files

_./.kitchen.local.yml_
```
driver:
  name: terraform
  backend_configurations:
    arm_subscription_id: SOME_GUID
    arm_client_id: SOME_GUID
    arm_client_secret: MY_SECRET
    arm_tenant_id: SOME_GUID
```
_./.ktichen.yml
```
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: azure

suites:
  - name: fondationportail
```

_./main.tf_
```
provider "azurerm" {
  version = "~> 1.15"
}

terraform {
  required_version = ">= 0.11.7"

  backend "azurerm" {
    key = "some.key"
    resource_group_name  = "some-rg-name,
    storage_account_name = "some-storage-account-name",
    container_name = "tfstate"
  }
}

```
