### ISSUE TITLE
Passing static InSpec attributes

### ISSUE THREAD

**Issue by bstock92** [newcontext-oss/kitchen-terraform#285]
(On kitchen-terraform 1.3.4)

We use a vendored InSpec profile for CIS compliance which accepts attributes which change the way that some rules are checked. InSpec only allows attributes to be set using the `--attrs` option in the command-line invocation, so these definitions must be passed in from the caller of InSpec. In this case, this is kitchen-terraform.

The current [verifier documentation](https://www.rubydoc.info/gems/kitchen-terraform/Kitchen/Verifier/Terraform) suggests that the `attrs` or `attrs_output` parameter of a `system` block within the `verifier` definition will define InSpec attributes with the values of Terraform outputs. I have two concerns about this:  
1. I do not currently have a `system` block in my `verifier`. Is one needed?  
2. I wish to define InSpec attributes with a static value, not one that depends on Terraform outputs. Is there a more elegant way to accomplish this than what is shown below?

With the help of some older v0.7.0 [documentation](https://www.rubydoc.info/gems/kitchen-terraform/0.7.0), I was able to achieve what I desired without a `system` block in my `verifier`. However, as you can see, it's not as clean as it could be, since as far as I can tell, the attribute needs to be defined once in the `verifier` block and once in the `suites` block.

```
verifier:
  name: terraform
  format: junit
  output: inspec_output.xml
  sudo: true
  groups:
    - name: core-rhel7
      hostnames: instance_ip
      username: packer
      # It seems that attributes are supposed to be linked to a TF output. Although in
      # this case it is neither necessary nor desirable, attribute definitions are not
      # passed to InSpec unless this attribute block contains a (pseudo) output
      # variable reference.
      attributes:
        REDHAT_REPOS: DEFINED_IN_SUITES_BELOW
        REDHAT_PUBKEY: DEFINED_IN_SUITES_BELOW

suites:
  - name: core-rhel7
    verifier:
      attributes:
        REDHAT_REPOS: []
        REDHAT_PUBKEY:
        - gpg-pubkey-fd431d51-4ae0493b
        - gpg-pubkey-2fa658e0-45700c69
        - gpg-pubkey-ef88bfcb-57ed5c5e
```

Is there a better way to do this, or is this acceptable given my requirements? Considering I can't find any mention of this in current documentation, is this syntax still supported?

### Update

It appears that it is not necessary to include each attribute in the `attributes` of `verifier`, as this appears to work as intended:

```
verifier:
  name: terraform
  format: junit
  output: inspec_output.xml
  sudo: true
  groups:
    - name: core-rhel7
      hostnames: instance_ip
      username: packer
      attributes:
        DUMMY_ATTRIBUTE: DUMMY_VALUE  # necessary for attributes in 'suite' block to be parsed

suites:
  - name: core-rhel7
    verifier:
      attributes:
        REDHAT_REPOS: []
        REDHAT_PUBKEY:
        - gpg-pubkey-fd431d51-4ae0493b
        - gpg-pubkey-2fa658e0-45700c69
        - gpg-pubkey-ef88bfcb-57ed5c5e
```

Is there any way to define the values of `REDHAT_REPOS` and `REDHAT_PUBKEY` without having a dummy attribute in `verifier`?
