### ISSUE TITLE
verifier on GCP platform

### ISSUE THREAD

**Issue by wyardley** [newcontext-oss/kitchen-terraform#286]
@aaron-lane: Figured this is different enough that I'll create a new issue; regarding some questions I had brought up in #263 

[in `test/integration/default/inspec.yml`]:
```yaml
name: inspec-gcp-integration-tests
inspec_version: '>= 2.2.10'
version: 1.0.0
depends:
  - name: inspec-gcp
    url: https://github.com/inspec/inspec-gcp/archive/master.tar.gz
supports:
  - platform: gcp
```
(so yes, I do have `platform: gcp` explicitly in the supported platforms).
```bash
% grep kitchen Gemfile.lock 
    kitchen-inspec (0.24.0)
      test-kitchen (~> 1.6)
    kitchen-terraform (4.0.1)
      test-kitchen (~> 1.23)
    test-kitchen (1.23.2)
  kitchen-inspec (~> 0.24.0)
  kitchen-terraform (~> 4.0)
  test-kitchen (~> 1.23)
```

My current `kitchen.yml`
```yaml
driver:
  name: "terraform"
  command_timeout: 1800
  root_module_directory: test

provisioner:
  name: "terraform"

transport:
  name: exec

platforms:
  - name: local

# Note: this doesn't yet work
# However, you can converge, and then run:
# bundle exec inspec exec -t gcp:// test/integration/default
verifier:
  name: inspec

suites:
  - name: "default"
```

Based on the examples, it seems like something like this should work:
```yaml
verifier:
  name: terraform
  systems:
    - name: local
      backend: gcp
      controls:
        - gke_cluster
```

```
% bundle exec kitchen verify 
-----> Starting Kitchen (v1.23.2)
$$$$$$ Running command `terraform version` in directory /Users/wby/git/terraform
       Terraform v0.11.10
       
$$$$$$ Terraform v0.11.10 is supported
bundler: failed to load command: kitchen (/usr/local/bin/kitchen)
KeyError: key not found: :connection_timeout
  /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-terraform-4.0.1/lib/kitchen/verifier/terraform.rb:181:in `fetch'
  /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-terraform-4.0.1/lib/kitchen/verifier/terraform.rb:181:in `block in transport_connection_options'
  /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-terraform-4.0.1/lib/kitchen/verifier/terraform.rb:180:in `tap'
  /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-terraform-4.0.1/lib/kitchen/verifier/terraform.rb:180:in `transport_connection_options'
  /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-terraform-4.0.1/lib/kitchen/verifier/terraform.rb:111:in `configure_inspec_connection_options'
  /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-terraform-4.0.1/lib/kitchen/verifier/terraform.rb:104:in `finalize_config!'
```

In this case, I'm running commands _locally_ against the GCP APIs.

As reported elsewhere, and as used in their docs, this works fine for me:
`bundle exec inspec exec -t gcp:// test/integration/default`
[I did try setting `user`, `host`, etc. to nulls or empty strings, but that didn't seem to help]

I recognize this may end up not being an issue with kitchen-terraform itself, but is there a way to accomplish the equivalent of the above command but via kitchen-terraform's verifier?

**Comment by wyardley** [comment]
Update: removing the exec transport (obvious in retrospect) seems to have helped, and this now works the way I expect:
```yaml
driver:
  name: "terraform"
  command_timeout: 1800
  root_module_directory: test

provisioner:
  name: "terraform"

platforms:
  - name: local

verifier:
  name: terraform
  systems:
    - name: local-gcp
      backend: gcp
      controls:
        - gke_cluster
```
