### ISSUE TITLE
kitchen-terraform destroy empty tf workspace - error

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#289]
Hello
from time to time I run into issues which I only can clear by removing .kitchen folder. Cleaning terraform temporary files does not fix it therefore I don't think it's related to terraform.

```
$$$$$$ Running command `terraform workspace select kitchen-terraform-default-test` in directory /home/myfolder/test/fixtures/default
       
       Workspace "kitchen-terraform-default-test" doesn't exist.
       
       You can create this workspace with the "new" subcommand.
$$$$$$ Running command `terraform workspace new kitchen-terraform-default-test` in directory /home/myfolder/test/fixtures/default
       Created and switched to workspace "kitchen-terraform-default-test"!
       
       You're now on a new, empty workspace. Workspaces isolate their state,
       so if you run "terraform plan" Terraform will not see any existing state
       for this configuration.
$$$$$$ Running command `terraform destroy -auto-approve -lock=true -lock-timeout=0s -input=false  -parallelism=10 -refresh=true  ` in directory /home/myfolder/test/fixtures/default
       data.aws_ami.test: Refreshing state...
       
       Error: Error applying plan:
       
       2 error(s) occurred:



$ bundle exec kitchen version
Test Kitchen version 1.23.2

```

**Comment by aaron-lane** [comment]
Hi @tbugfinder!

Are you able to share the omitted error messages?

**Comment by ramgad** [comment]
I've received the same error and wondering if any of you have recommendation on how to overcome this problem? Thank you!

**Comment by aaron-lane** [comment]
@ramgad @tbugfinder if either of you are able to share your projects, or at least the Kitchen configuration files and complete output, that would be very helpful for triaging this issue.

**Comment by tbugfinder** [comment]
Sorry for the delay.
Unfortunaltely I wasn't able to find the trigger when this error is really raised. After a cleanup of .kitchen folder I can execute it again.

We use a workspace within terrraform.
```
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
- name: aws

verifier:
  name: terraform

suites:
- name: default
  driver:
    root_module_directory: test/fixtures/default
  verifier:
    systems:
    - name: aws
      backend: aws
      reporter:
      - cli
      - json:test/integration/default/myinspec.json
```

There's a .tf file which includes a lifecycle-keeper setting:
```
provider "random" {
  version = "2.0.0"
}

resource "random_string" "random_output" {
  keepers {
    lifecycle = "${terraform.workspace}"
  }

  length  = 20
  upper   = false
  lower   = true
  special = false
}

locals {
  ro = "${random_string.random_output.result}"
}
```

[kitchen.bugreport.log.txt](https://github.com/newcontext-oss/kitchen-terraform/files/2629842/kitchen.bugreport.log.txt)
