### ISSUE TITLE
`bundle exec kitchen verify` does not execute tests

### ISSUE THREAD

**Issue by lmayorga1980** [newcontext-oss/kitchen-terraform#316]
**test-kitchen:** `1.24.0`
**terraform:** `0.11.11`
**kitchen.yml**
```
driver:
  name: terraform
  command_timeout: 1000
  variable_files:
    - my-variables.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

terraform:
  name: ssh
  ssh_key: ./cert/terraform.key
  username: ubuntu

verifier:
  name: terraform
  format: doc
  groups:
    - name: dockers
      controls:
      - operating_system
      hostnames: docker_addresses

suites:
  - name: example
```

**directory structure**

```
├── 0.main.tf
├── Gemfile
├── cert
│   ├── terraform.key
│   └── terraform.key.pub
├── files
│   ├── docker-setup.sh
├── my-variables.tfvars
├── output.tf
├── terraform.tfstate
├── terraform.tfstate.backup
├── terraform.tfstate.d
│   ├── kitchen-terraform-example-ubuntu
│   │   └── terraform.tfstate
│   └── test
├── test
│   └── integration
│       └── example
│           ├── controls
│           │   └── operating_system_spec.rb
│           ├── inspec.lock
│           └── inspec.yml
└── variables.tf
```

**inspec.yml**

```
---
name: example
```

`bundle exec kitchen verify` does not execute my test but kitchen-terraform is able to create the infrastructure correctly.

**Comment by aaron-lane** [comment]
Hello again @lmayorga1980.

Regarding your `kitchen.yml`, the root level `terraform` key is not valid. I suspect that was supposed to be `transport`, but that key is no longer necessary so it can be safely omitted.

As for the error message, it indicates that `./cert/terraform.key` is in ED25519 format and additional gems are required in order to use the key for SSH connections. Adding the following to your `Gemfile` should solve the problem:

```ruby
gem "bcrypt_pbkdf", "~> 1.0"
gem "rbnacl", "~> 4.0"
gem "rbnacl-libsodium", "~> 1.0"
```

**Comment by lmayorga1980** [comment]
@aaron-lane,

I've had to isolate the issue by generating a key with an old format and got the following...

**kitchen.yml**

```yaml
---
driver:
  name: terraform
  command_timeout: 1000
  variable_files:
    - my-variables.tfvars

provisioner:
  name: terraform

transport:
  name: ssh
  ssh_key: ./cert/terraform.key
  username: ubuntu
  port: 22

verifier:
  name: terraform
  systems:
    - name: example
      backend: ssh
      hosts_output: haproxy_address
      key_files:
        - cert/terraform.key
      controls:
        - operating_system
      user: ubuntu

platforms:
  - name: ubuntu

suites:
  - name: example
```

**Gemfile**

```
source "https://rubygems.org/"

gem 'kitchen-terraform'
gem 'test-kitchen'

```

**output**
```

Profile: default
Version: (not specified)
Target:  ssh://ubuntu@10.82.132.29:22

  ✔  operating_system: Command: `lsb_release -a`
     ✔  Command: `lsb_release -a` stdout should match /Ubuntu/


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 1 successful, 0 failures, 0 skipped
       Finished verifying <example-ubuntu> (0m1.74s).
-----> Kitchen is finished. (0m3.47s)

```

I will probably come back and check the openssl new format with the newer gems.

Good stuff 👍 

Thank you.
