### ISSUE TITLE
Failed to complete #verify action

### ISSUE THREAD

**Issue by gbergere** [newcontext-oss/kitchen-terraform#321]
Hi, 

I'm not sure why, as I'm using pretty much the same config, I'm using in [here](https://github.com/gbergere/micro-service-as-code). However in this project it fails has below.

**What am I trying to achieve?**
I have a GKE cluster module which I want to test with a local call to a dummy services running on it (as you can see below my `kitchen.yml`.

```
# file: kitchen.yml
---
driver:
  name: terraform
  command_timeout: 1200  # 10 minutes (default: 600)
  root_module_directory: test/fixtures/wrapper

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: gke
    verifier:
      systems:
        - name: local
          backend: local
          controls:
            - http_root_endpoint

suites:
  - name: default
    lifecycle:
      pre_verify:
        # Wait for Pods to come up
        - local: sleep 90
```

The idea is to simply call the root endpoint from an nginx deployed on it (as below).

```
#file: test/integration/default/controls/http_root_endpoint_spec.rb
url = attribute("endpoint")

control 'http_root_endpoint' do
  describe http(url) do
    its('status') { should eq 200 }
    its('body') { should cmp "Hello World!" }
  end
end
```

```
#file: test/integration/default/inspect.yml
---
name: default

attributes:
  - name: endpoint
    type: string
    required: true
```

Also here is my CI job:
```
#file: .circleci/config.yml
---
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.2
    environment:
      TERRAFORM_VERSION: 0.11.11
    steps:
      - run:
          name: Install terraform binary
          command: |
            wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
            rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - checkout
      - run:
          name: Install ruby dependencies
          command: bundle install
      - run:
          name: Initialize kitchen-terraform
          command: bundle exec kitchen create
      - run:
          name: Run kitchen-terraform to test our stack
          command: bundle exec kitchen verify
      - run:
          name: Remove all terraform resources
          command: bundle exec kitchen destroy
          when: always


workflows:
  "test":
    jobs:
      - test
```

**Failure**

```
>> bundle exec kitchen verify -l=debug
       ...     
       Apply complete! Resources: 14 added, 0 changed, 0 destroyed.
       
       Outputs:
       
       endpoint = http://34.76.26.28/nginx
       Finished converging <default-gke> (5m41.36s).
-----> Setting up <default-gke>...
D      <default-gke> is synchronizing on Kitchen::Driver::Terraform#setup
D      <default-gke> is messaging Kitchen::Driver::Terraform#setup
       Finished setting up <default-gke> (0m0.00s).
D      [local command] BEGIN (sleep 90)
D      [local command] END (1m29.25s)
-----> Verifying <default-gke>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-default-gke` in directory /home/circleci/project/test/fixtures/wrapper
$$$$$$ Running command `terraform output -json` in directory /home/circleci/project/test/fixtures/wrapper
       {
           "endpoint": {
        "sensitive": false,
        "type": "string",
        "value": "http://34.76.26.28/nginx"
           }
       }
Option backend_cache is disabled
Resolve {:path=>"/home/circleci/project/test/integration/default"} into cache /home/circleci/.inspec/cache
Dependency does not exist in the cache {:path=>"/home/circleci/project/test/integration/default"}
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Don't understand inspec profile in /home/circleci/project/test/integration/default, it doesn't look like a supported profile structure.] on default-gke
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Don't understand inspec profile in /home/circleci/project/test/integration/default, it doesn't look like a supported profile structure.] on default-gke
D      ----------------------
D      ------Backtrace-------
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:183:in `report_errors'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:174:in `run_action'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /usr/local/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command/action.rb:34:in `call'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/cli.rb:52:in `perform'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/bin/kitchen:13:in `block in <top (required)>'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/bin/kitchen:13:in `<top (required)>'
D      /usr/local/bundle/bin/kitchen:21:in `load'
D      /usr/local/bundle/bin/kitchen:21:in `<top (required)>'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
D      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
D      /usr/local/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
D      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
D      /usr/local/bundle/bin/bundle:104:in `load'
D      /usr/local/bundle/bin/bundle:104:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #verify action: [Don't understand inspec profile in /home/circleci/project/test/integration/default, it doesn't look like a supported profile structure.] on default-gke
D      ----------------------
D      ------Backtrace-------
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/profile.rb:64:in `for_path'
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/profile.rb:73:in `for_fetcher'
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/profile.rb:79:in `for_target'
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/runner.rb:197:in `add_target'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/inspec.rb:70:in `initialize'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/inspec_without_hosts.rb:29:in `new'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/inspec_without_hosts.rb:29:in `exec'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/system.rb:101:in `verify'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:194:in `verify'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:88:in `block in call'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:87:in `each'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:87:in `call'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:458:in `block in verify_action'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:551:in `synchronize_or_call'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:513:in `block in action'
D      /usr/local/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:512:in `action'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:450:in `verify_action'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:162:in `verify'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #verify action: [Don't understand inspec profile in /home/circleci/project/test/integration/default, it doesn't look like a supported profile structure.]
D      ----------------------
D      ------Backtrace-------
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/profile.rb:64:in `for_path'
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/profile.rb:73:in `for_fetcher'
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/profile.rb:79:in `for_target'
D      /usr/local/bundle/gems/inspec-3.5.0/lib/inspec/runner.rb:197:in `add_target'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/inspec.rb:70:in `initialize'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/inspec_without_hosts.rb:29:in `new'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/inspec_without_hosts.rb:29:in `exec'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/terraform/system.rb:101:in `verify'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:194:in `verify'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:88:in `block in call'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:87:in `each'
D      /usr/local/bundle/gems/kitchen-terraform-4.3.0/lib/kitchen/verifier/terraform.rb:87:in `call'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:458:in `block in verify_action'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:551:in `synchronize_or_call'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:513:in `block in action'
D      /usr/local/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:512:in `action'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:450:in `verify_action'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:162:in `verify'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /usr/local/bundle/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
Exited with code 20
```
