### ISSUE TITLE
Does not work with chefdk 3.9.0

### ISSUE THREAD

**Issue by robkinyon-roivant** [newcontext-oss/kitchen-terraform#335]
Running on Amazon Linux/2 running ruby2.4.4p296 (installed from Amazon Linux Extras). I've installed ChefDK 3.9.0-1.el7 downloaded from https://downloads.chef.io/chefdk/

I have an empty directory with just the following files:
```
Gemfile:
source 'https://rubygems.org' do
  gem 'kitchen-terraform'
end

.kitchen.yml:
---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

verifier:
  name: terraform
  format: doc
  groups:
    - name: default
      controls:
        - first aws test

suites:
  - name: default
```
I did a `bundle install` (which ran clean). Then, I tried the following commands and each fails (error inline):
* `kitchen converge`
```
-----> Starting Kitchen (v1.24.0)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'terraform' driver from the load path. Did you mean: azurerm, digitalocean, dokken, dummy, ec2, exec, gce, hyperv, proxy, vagrant ? Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
* `bundle exec kitchen converge`
```
Could not find addressable-2.6.0 in any of the sources
Run `bundle install` to install missing gems.
```
* `bundle exec ~/bin/kitchen converge`
```
-----> Starting Kitchen (v1.24.0)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'terraform' driver from the load path. Did you mean: dummy, exec, proxy ? Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

What am I missing? Is there a version of the ChefDK package I should be using instead?
