### ISSUE TITLE
junit output for inspec

### ISSUE THREAD

**Issue by bcarpio** [newcontext-oss/kitchen-terraform#364]
When I have the following in .kitchen.yml my inspec tests run correctly when running `kitchen verify`:

```
verifier:
  name: terraform
  format: doc
```

However when I switch format to junit and run `kitchen verify`

```
verifier:
  name: terraform
  format: junit
```

My tests still run correctly but I don't get junit output, it's like this option is being ignored. Is there a way to get the terraform verifier to output junit?

**Comment by bcarpio** [comment]
I figured this out:

```
suites:
  - name: default
    verifier:
      systems:
        - name: <module_name>
          backend: local
          reporter:
            - cli
            - junit:test/integration/default/junit/junit.xml
```

Closing this but added the resolution for the next person looking for it.
