### ISSUE TITLE
profile_locations is ignored

### ISSUE THREAD

**Issue by anniehedgpeth** [newcontext-oss/kitchen-terraform#366]
Hi, I'm new to kitchen-terraform and have a couple of questions. 

1) Is there a way to run two different InSpec profiles in the same suite without depending on each other? I want to use one with an *ssh* backend and another with *azure*, so they're not compatible to run together. But I'd love it if I could just run them back to back in two different InSpec sessions. I've been trying, but that leads me to my second question. 

2) What's the trick to getting `profile_locations` to work? I want to put two different profiles in my `<Kitchen root>/test/integration/<suite name>` directory, each in its own directory, and use `profile_locations` to point to them individually. But it just ends up ignoring my `profile_locations` path and tells me `it doesn't look like a supported profile struct`. 

This is my module's directory structure:
```
│   Gemfile
│   main.tf
│   outputs.tf
│   README.md
│   variables.tf
│
├───files
│       cloud-config.yaml
│       init.sh
│
└───test
    ├───fixtures
    │   └───master-test
    │       │   dependencies.tf
    │       │   locals.tf
    │       │   main.tf
    │       │   outputs.tf
    │       │   variables.tf
    │       │
    │       └───files
    │               init.groovy
    │
    └───integration
        └───master-test
            ├───master-azure-test
            │   │   inspec.yml
            │   │
            │   └───controls
            │           azure_test.rb
            │
            └───master-vm-test
                │   inspec.yml
                │
                └───controls
                        vm_test.rb
```

This is my `.kitchen.yml`:
```
driver:
  name: terraform
  root_module_directory: test/fixtures/master-test
  command_timeout: 1200

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: vm
      backend: ssh
      port: 22
      hosts_output: master_vm_private_ip_address
      user: localadmin
      password: 'P2ssw0rd'
      profile_locations:
        - test/integration/master-test/master-vm-test
    - name: azure
      backend: azure
      profile_locations:
        - test/integration/master-test/master-azure-test

platforms:
  - name: terraform

suites:
  - name: master-test
```

Thanks!

**Comment by anniehedgpeth** [comment]
Got it working!

For anyone searching later, it seems that you simply need to put support for both platform and os-family in the kitchen.yml, add all controls to the same profile (or depend on another profile), and specify which controls to run for each system.

.kitchen.yml
```driver:
  name: terraform
  root_module_directory: test/fixtures/master-test
  command_timeout: 1200

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: vm
      backend: ssh
      port: 22
      hosts_output: master_vm_private_ip_address
      user: localadmin
      password: 'P2ssw0rd'
      controls:
        - vm
    - name: azure
      backend: azure
      controls:
        - master-azure

platforms:
  - name: terraform

suites:
  - name: master-test
```

module directory structure:
```│   Gemfile
│   main.tf
│   outputs.tf
│   README.md
│   variables.tf
│
├───files
│       cloud-config.yaml
│       init.sh
│
└───test
    ├───fixtures
    │   └───master-test
    │       │   dependencies.tf
    │       │   locals.tf
    │       │   main.tf
    │       │   outputs.tf
    │       │   variables.tf
    │       │
    │       └───files
    │               init.groovy
    │
    └───integration
        └───master-test
            └───master-test
                │   inspec.yml
                │
                └───controls
                        azure_test.rb
                        vm_test.rb
```

inspec.yml

```
---
name: master-test
version: 0.1.0
depends:
  - inspec-azure:
    git: https://github.com/inspec/inspec-azure.git
supports:
  - platform: azure
  - os-family: linux
```

**Comment by aaron-lane** [comment]
Hi @anniehedgpeth! Thank you for your interest in the project.

Did you try using `profile_locations` after updating the `inspec.yml`
 files to define the supported configuration? The original configuration appears to be valid beyond the issue about the supported profile struct.

This issue also makes me think it would be more intuitive to default the configuration to assume different profile locations for each system. What do you think?

**Comment by anniehedgpeth** [comment]
No, because it defeated the purpose. The reason that I wanted to use `profile_locations` was to use two separate profiles in nested directories under `test/integration/master-test`. So I would have had two separate `inspec.yml` files, one for each profile. But every time, it just looked in the default directory `test/integration/master-test`.

Yes, I think it would be good to default the profile locations for each system to maybe `test/integration/<suite_name>/<system_name>`, but I still think there might be a bug in `profile_locations` because it kept looking in the default directory every time I tried it with a different value, whether it be a local path or a git link. (I was just fortunate to not have to use it after all because InSpec didn't have the limitation that I thought it had.)

I also tried adding a new systems entry like so:

```
    - name: demo
      backend: ssh
      port: 22
      hosts_output: master_vm_private_ip_address
      user: localadmin
      password: <%= ENV['TK_PASS'] %>
      profile_locations:
        - https://github.com/anniehedgpeth/demo_profile
```

...but it still tried to look in the `test/integration/master-test` directory.
