### ISSUE TITLE
ConnectionTimeout

### ISSUE THREAD

**Issue by dwizzle204** [newcontext-oss/kitchen-terraform#373]
Is there anyway to specify connection attempts in the verifier?
It appears like kitchen is trying to login before the VM is accepting ssh connections....
If I don't do the destroy I can ssh into the server using the proper account without issue. 

[SSH] connection failed, retrying in 1 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       [SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 10.84.4.29:22>)
       [SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 10.84.4.29:22>)
       [SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 10.84.4.29:22>)
$$$$$$ [SSH] connection failed, terminating (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 10.84.4.29:22>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.

Example kitchen file:
---
driver:
  name: terraform
  command_timeout: 600
  color: true
  root_module_directory: terraform/

provisioner:
  name: terraform

platforms:
- name: rhel7
  os_type: linux

transport:
  name: ssh
  connection_retries: 600
  connection_retry_sleep: 10
  max_wait_until_ready: 6000

verifier:
  name: terraform
  systems:
    - name: image
      backend: ssh
      user: packer
      key_files:
        - packer-ssh-key
      hosts_output: host_ip
      sudo: true
      reporter:
        - junit:inspec_output.xml
      input_files:
        - test/integration/image/attributes.yml  # attributes that were previously passed in here, now need to be in a file

suites:
  - name: image

**Comment by aaron-lane** [comment]
Hi @dwizzle204! Thank you for your interest in the project!

If there is a sufficient delay between `kitchen converge` and `kitchen verify`, does the connection succeed or does it only succeed when executed manually?

Transport plugins are not currently used by the Kitchen-Terraform verifier plugin as it relies on InSpec to handle connection responsibilities. I think you should be able to use the `proxy_command` attribute of the system to control connection retry logic, though admittedly the solution is convoluted as it relies on Kitchen config interpolation.

```yaml
driver:
  name: terraform
  command_timeout: 600
  color: true
  root_module_directory: terraform/

provisioner:
  name: terraform

platforms:
  - name: rhel7
    os_type: linux

verifier:
  name: terraform
  systems:
    - name: image
      backend: ssh
      proxy_command: ssh packer@<%= `terraform output host_ip -state terraform/terraform.tfstate.d/terraform.tfstate` %> -o 'ConnectionAttempts 10' -o 'ConnectTimeout 5' -W %h:%p
      user: packer
      key_files:
        - packer-ssh-key
      hosts_output: host_ip
      sudo: true
      reporter:
        - junit:inspec_output.xml
      input_files:
        - test/integration/image/attributes.yml

suites:
  - name: image
```
