### ISSUE TITLE
5.2 and 5.3  not compatible with InSpec 4.6.4

### ISSUE THREAD

**Issue by frank815** [newcontext-oss/kitchen-terraform#395]
**Issue**: Getting an error when reading Terraform output in a control test.
This is only reproducible with InSpec 4.6.4. I was able to get around this when the latest installation of inspec 4.18.104. 

Might be worth just updating the docs. I was banging my head on this for a couple days. =) 

**Error Message**
```
 can't convert Inspec::Input::NO_VALUE_SET to Array (Inspec::Input::NO_VALUE_SET#to_ary gives Inspec::Input::NO_VALUE_SET)
```

**Steps to Reproduce**
1. Add the configuration below. 
2. run `kitchen converge`
3. run `kitchen verify`

**Configuration**
`Gemfile`
```
source "https://rubygems.org/" do
    gem(
      "kitchen-terraform",
      "~> 5.3.0"
    )
    gem(
      "inspec",
      "4.6.4"
    )
  end
```
`outputs.tf` 
```
output "bucket_arn" {
    value = module.default.bucket_arn
}

output "db_name" {
    value = module.default.db_name
}
```

`test.rb`
```
control "bucket_arn" do
    puts "Bucker ARN: "
    puts attribute("bucket_arn")
    puts attribute("db_name")
end
```
`kitchen.yml`
```
---
driver:
  name: "terraform"
  root_module_directory: "test/example"

provisioner:
  name: "terraform"

verifier:
  name: "terraform"

platforms:
  - name: centos-7

suites:
  - name: default
    verifier:
      systems:
        - name: default
          backend: local
          controls:
            - bucket_arn
```
