### ISSUE TITLE
No Test executed with gcp backend

### ISSUE THREAD

**Issue by wudong** [newcontext-oss/kitchen-terraform#420]
I'm trying to get kitchen-terraform work with a gcp terrafrom module. 
Even though the terraform part works great but the inspec test are not executed.

```
verifying the 'insepc-gcp' system
Profile:  GCP InSpec Profile (depotglobal)
Version: 0.1.0
Target:  gcp://sa-build-test-0c27@dp-global-test-0c27.iam.gserviceaccount.com

     No tests executed.

Profile: Google Cloud Platform Resource Pack (inspec-gcp)
Version: 1.8.0
Target:  gcp://sa-build-test-0c27@dp-global-test-0c27.iam.gserviceaccount.com

     No tests executed.

```

My Kitchen.yml
```
---
driver:
  name: "terraform"
  command_timeout: 1800
  verify_version: false

provisioner:
  name: "terraform"

platforms:
  - name: "local"

verifier:
  name: "terraform"
  color: false

suites:
  - name: "dpglobal"
    driver:
      root_module_directory: test
    verifier:
      systems:
      - name: inspec-gcp
        backend: gcp
        attrs_outputs:
          gcp_project_id: project_id
        controls:
          - vm

```

My inspec.yml
```
name: dpglobal
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '>= 2.3.5'
attributes:
- name: gcp_project_id
  required: true
  description: 'The GCP project identifier.'
  type: string
depends:
- name: inspec-gcp
  git: https://github.com/inspec/inspec-gcp.git
  tag: v0.10.0
```

If i run 
```
inspec exec . -t gcp:// --attrs attributes.yml
```
The test does get executed. 

It looks like kitchen-terraform append the service account that i'm running the test with into the target. and somehow, the test get skipped. 

Anyone can advice here? it bothers me for a few days now.
