### ISSUE TITLE
junit(2) is not a valid reporter type

### ISSUE THREAD

**Issue by wyardley** [newcontext-oss/kitchen-terraform#435]
kitchen-terraform 5.6.0
kitchen-inspec 2.3.0
inspec(-bin) 4.26.0

I'm still having issues similar to https://github.com/inspec/inspec/issues/5243
It seems like this may now be an issue with kitchen-terraform itself (see https://github.com/inspec/kitchen-inspec/issues/272)

Let me know if I should be using the `inspec` verifier directly now, or if there's some other way to pass additional arguments to `inspec` when using this one.

# Steps to Reproduce:
`bundle exec kitchen verify`
my config currently looks like this:
```yaml
provisioner:
  name: "terraform"

platforms:
  - name: local

verifier:
  name: terraform
  systems:
    - name: remote-gcp
      backend: gcp
      reporter:
        - progress
        - json:/tmp/remote_gcp_inspec.json
        - junit2:/tmp/remote_gcp_inspec.xml
      controls:
        - foo
        - bar
    - name: local-outputs
      backend: local
      reporter:
        - progress
        - json:/tmp/local_inspec.json
      controls:
        - foo
        - bar
```

# Expected Result:
a junit report is created

# Actual Result:
```
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: ['junit' is not a valid reporter type.] on default-local
```

Same error whether I specify `junit` or `junit2`.
Note: json reporter does seem to work as expected here.
