### ISSUE TITLE
Kitchen-Terraform not agreeing port 80 is listening

### ISSUE THREAD

**Issue by mihirvijdeshpande** [newcontext-oss/kitchen-terraform#446]
We're trying out Kitchen to test our Terraform - AWS code.
We're trying to test if port 80 is open via SSH backend on an EC2 instance.

Note that the same also fails for `{ should_not be_listening }` without any changes to the terraform code / infrastructure

Here's the `.rb` file:

    control 'httpd' do
      describe port(80) do
        it { should be_listening }
      end
    end

This is what we get as the output of `kitchen verify` / `bundle exec kitchen verify` :

    Failed examples:

    rspec /var/lib/gems/2.7.0/gems/inspec-core-4.25.1/lib/inspec/rule.rb[1:1] # Port 80 is expected to be listening

Here's the output of `netstat -tunlep`

    Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
    tcp6       0      0 :::80                   :::*                    LISTEN      0          23704      -

Here's the output of `ss -tunlep`

    Netid           State            Recv-Q           Send-Q                            Local Address:Port                       Peer Address:Port           Process
    tcp             LISTEN           0                9                                             *:80                                    *:*               ino:23704 sk:5 v6only:0 <->

And Finally, here's our `user-data.sh` file that ensures busybox http service is running and listening at port 80:

    #!/bin/bash
    set -e
    sudo apt-get -qq install net-tools -y

    exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
    
    # The variables below are filled in using Terraform interpolation
    echo "${instance_text}" > index.html
    sudo nohup busybox httpd -f -p "${instance_port}" &

I added code to install netstat because it wasn't shipped with default ami.

**versions**\
Ubuntu 20.04\
Test Kitchen version 2.10.0\
ruby 2.7.0p0\
Terraform v0.13.5\
provider registry.terraform.io/hashicorp/aws v3.30.0\
provider registry.terraform.io/hashicorp/template v2.2.0

**Comment by aaron-lane** [comment]
Hi @mihirvijdeshpande! Thank you for your interest in the project.

> Note that the same also fails for { should_not be_listening } without any changes to the terraform code / infrastructure

This statement confuses me. Are you saying that if you run the opposite test on the same machine, that 80 port should not be listening, then InSpec fails saying that it is listening?

Are you able to share a repository which reproduces this issue?

**Comment by mihirvijdeshpande** [comment]
> This statement confuses me. Are you saying that if you run the opposite test on the same machine, that 80 port should not be listening, then InSpec fails saying that it is listening?

That's correct! When I check the infra, the port is open. On testing for `should be_listening` it returns `false`. Same infra returns `false` for `should_not be_listening`

I think at least one of them should return true.

We will not be able to share the repository, however, if you let me know what parts of code you need to look at I can share the snippets with you.

**Comment by aaron-lane** [comment]
The behaviour you're describing sounds like a bug within [InSpec](https://github.com/inspec/inspec); it really doesn't make sense how both the listening and not listening tests return `false` on the same machine. Out of curiosity, have you tried running both tests in the same `describe` block?

If you can share your Kitchen configuration file (`kitchen.yml` or `.kitchen.yml`) then we may be able to spot a misconfiguration that is causing this, but it does seem like InSpec is simply misbehaving.

**Comment by mihirvijdeshpande** [comment]
Thanks for your input! I did not try putting both in the same describe block. I was trying to replace one with another and running verify and both returned false. After seeing your input I tried both in same describe block, and it worked like expected. Every verify after that also works as expected. At this point I would keep an eye out for the issue and if I face it again, will get in touch with InSpec.

Thanks for all the help!

Here's my `.kitchen.yml` file anyway if you notice something that I can improve on:

```
---
driver:
  name: terraform
  variable_files:
    - terraform.tfvars
  region: "us-east-1"

provisioner:
  name: terraform

platforms:
  - name: ubuntu

verifier:
  name: terraform
  systems:
    - name: default
      controls:
        - operating_system
        - httpd
      backend: ssh
      user: <redacted user>
      key_files:
        - <redacted-filename>.pem
      hosts_output: private_ip
      reporter:
        - documentation
    - name: aws
      controls:
        - s3
        - lambda
      backend: aws
      reporter:
        - documentation

suites:
  - name: default
```
