### ISSUE TITLE
BUG: built-in variable in kitchen.yml not working

### ISSUE THREAD

**Issue by luckeyca** [newcontext-oss/kitchen-terraform#472]
%{platform} and %{suite} in kitchen.yml not parsed for the junit report file name.
NO error running the "kitchen test" command at all.

kitchen diagnose command also shows the variables as not parsed.

expected file name: `terraform-default-junit.xml`
actual actual file: `%{platform}-%{suite}-junit.xml`

```sh
bash-5.1# ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-musl]

bash-5.1# kitchen version
Test Kitchen version 3.3.2

bash-5.1# terraform version
Terraform v1.2.8
on linux_amd64
```

-------------------
kitchen.yml

```yaml
---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: terraform

verifier:
   name: terraform
   inspec_tests:
       - test/integration/%{suite} # This is the default directory for the test suite.
   systems:
      - name: basic
        backend: local
        reporter:
           - cli
           - junit2:test/reports/%{platform}-%{suite}-junit.xml

suites:
  - name: default
    driver:
      root_module_directory: test/fixtures/default
```
