### ISSUE TITLE
Should kitchen destroy run in the reverse order?

### ISSUE THREAD

**Issue by brettcurtis** [newcontext-oss/kitchen-terraform#474]
I'm working on a test suit for some Kubernetes work:

```yaml
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: gcp

# You will want to run the tests in serially, they will fail if run in parallel. You will also want to destroy
# the default-kubernetes-onboarding-gcp suite first since it creates objects in the cluster. If you don't you
# will have some state files to clean up.

suites:
  - name: setup_kubernetes_onboarding
    driver:
      root_module_directory: test/fixtures/setup
    verifier:
      color: true

  - name: default_kubernetes_onboarding
    driver:
      root_module_directory: test/fixtures/default_kubernetes_onboarding
    verifier:
      color: true
```

The setup suite builds the k8s cluster and does a few other tasks and the onboarding suite deploys some stuff to the k8s cluster, namespaces, service accounts etc.

kitchen converge run fines since it's top to bottom and runs sequentially by default. However, destroy also does the same in this use case destroying my k8s cluster before removing the onboarding resources.  At this point I'm just updating the READMEs, code comments and our workflows to destroy onboarding before setup be in my magical ability to see the future, module developers are going to be running destroy and stuck with a state file mess :)
