### ISSUE TITLE
Support for localstack AWS testing

### ISSUE THREAD

**Issue by meltingturret** [newcontext-oss/kitchen-terraform#519]
Any thoughts on an easy way for configure terraform kitchen to converge against localstack? For verification I am using awsspec and the verifier does respond to http_proxy configuration fine but the provisioner does not.

```
driver:
  name: "terraform"
  variable_files:
    - testing.tfvars

provisioner:
  name: "terraform"

platforms:
  - name: "aws"

verifier:
  name: "awspec"

suites:
  - name: default
    verifier:
      #default_pattern: true
      patterns:
        - spec/**/*_spec.rb
```
When I run `bundle exec kitchen converge` aws is updated and not localstack running on http://localhost:4566.

I want to avoid adding this in the aws provider:

```
provider "aws" {
  endpoints {
    ec2            = "http://localhost:4566"
    s3             = "http://s3.localhost.localstack.cloud:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
  }
}
```
