### ISSUE TITLE
kitchen doctor warnings: client 'terraform' does not exist

### ISSUE THREAD

**Issue by wyardley** [newcontext-oss/kitchen-terraform#520]
Let me know if this is actually a test kitchen vs kitchen-terraform issue, and I'll file a  bug upstream

`kitchen doctor` gives me the following error

```
>>>>>> client 'terraform' does not exist
>>>>>> client 'terraform' is not executable
>>>>>> client 'terraform' does not exist
>>>>>> client 'terraform' is not executable
```

config:
```yaml
driver:
  name: terraform

transport:
  name: terraform
  root_module_directory: test/integration

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: gcp-remote
      backend: gcp
      reporter:
        - cli
        - html:/tmp/reports/gcp_remote_inspec.html
        - junit2:/tmp/reports/gcp_remote_inspec.xml
  inspec_tests:
    - test/integration/default

platforms:
  - name: terraform

suites:
  - name: default
```
