### ISSUE TITLE
kitchen-verifier-awspec plugin

### ISSUE THREAD

**Issue by neillturner** [newcontext-oss/kitchen-terraform#83]
I've built a new plugin for awspec that could be very useful to use with kitchen-terraform to do verification of aws infrastructure. 
See:   https://github.com/neillturner/kitchen-verifier-awspec

just need to put in  .kitchen.yml file: 

```yaml
verifier:
  name: awspec

suites:
  - name: base
    verifier:
      patterns:
      - spec/test_spec.rb
```
